NewsWebsite/Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsWebsite.Common.Extensions;
using NewsWebsite.Common.Attributes;
using NewsWebsite.Data.Contracts;
using NewsWebsite.Entities;
using NewsWebsite.ViewModels.DynamicAccess;
using NewsWebsite.ViewModels.News;

namespace NewsWebsite.Areas.Admin.Controllers
{
    [DisplayName("مدیریت اخبار")]
    public class NewsController : BaseController
    {
        private const string NewsNotFound = "خبر یافت نشد.";
        private readonly IUnitOfWork _uw;
        private readonly IWebHostEnvironment _env;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _context;      
        public NewsController(IUnitOfWork uw, IMapper mapper, IWebHostEnvironment env, IHttpContextAccessor context)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));

            _env = env;
            _env.CheckArgumentIsNull(nameof(_env));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));

            _context = context;
            _context.CheckArgumentIsNull(nameof(_context));
        }


        [HttpGet, DisplayName("مشاهده"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> GetNews(string search, string order, int offset, int limit, string sort)
        {
            List<NewsViewModel> news;
            int total = _uw.BaseRepository<News>().CountEntities();

            if (!search.HasValue())
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "ShortTitle")
            {
                if (order == "asc")
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "ShortTitle", search, null, null);
                else
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "ShortTitle desc", search, null, null);
            }
            else if (sort == "بازدید")
            {
                if (order == "asc")
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfVisit", search, null, null);
                else
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfVisit desc", search, null, null);
            }
            else if (sort == "لایک")
            {
                if (order == "asc")
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfLike", search, null, null);
                else
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfLike desc", search, null, null);
            }
            else if (sort == "دیس لایک")
            {
                if (order == "asc")
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfDisLike", search, null, null);
                else
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfDisLike desc", search, null, null);
            }
            else if (sort == "تاریخ انتشار")
            {
                if (order == "asc")
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "PublishDateTime", search, null, null);
                else
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "PublishDateTime desc", search, null, null);
            }
            else if (sort == "نظرات")
            {
                if (order == "asc")
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfComments", search, null, null);
                else
                    news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "NumberOfComments desc", search, null, null);
            }
            else
                news = await _uw.NewsRepository.GetPaginateNewsAsync(offset, limit, "PublishDateTime desc", search, null, null);

            if (search != "")
                total = news.Count();

            return Json(new { total = total, rows = news });
        }


        [HttpGet, DisplayName("درج و ویرایش"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> CreateOrUpdate(string newsId)
        {
            NewsViewModel newsViewModel = new NewsViewModel();
            ViewBag.Tags = _uw.Context.Tags.Select(t => t.TagName).ToList(); // مقداردهی تگ با تگ مقداردهی شده در سمت کاربر مرتبط است
            newsViewModel.NewsCategoriesViewModel = new NewsCategoriesViewModel(await _uw.CategoryRepository.GetAllCategoriesAsync(), null);

            if (newsId.HasValue())
            {
                var news = await (from n in _uw.Context.News  // مقداردهی شده و درون این نویگیشن پراپرتی قرار می گیرد TagId و NewsId لیستی از
                                    join e in _uw.Context.NewsCategories on n.NewsId equals e.NewsId into nc
                                  from nct in nc.DefaultIfEmpty()
                                    join w in _uw.Context.NewsTags on n.NewsId equals w.NewsId into bc
                                  from bct in bc.DefaultIfEmpty()
                                    join t in _uw.Context.Tags on bct.TagId equals t.TagId into cg
                                  from cog in cg.DefaultIfEmpty()
                                  where (n.NewsId == newsId)
                                  select new NewsViewModel
                                  {
                                      NewsId = n.NewsId,
                                      Title = n.Title,
                                      Abstract = n.Abstract,
                                      Description = n.Description,
                                      PublishDateTime = n.PublishDateTime,
                                      IsPublish = n.IsPublish,
                                      ImageName = n.ImageName,
                                      IsInternal = n.IsInternal,
                                      IdOfCategories = nct != null ? nct.CategoryId : "",
                                      Url = n.Url,
                                      NameOfTags = cog != null ? cog.TagName : "",
                                  }).ToListAsync(); // استفاده کرده ایم Left Outer Join در اینجا لیستی داریم که به ازای هر تگ اطلاعات خبر تکرار می شود زیرا از

                if (news != null)
                {
                    newsViewModel = _mapper.Map<NewsViewModel>(news.FirstOrDefault());

                    if (news.FirstOrDefault().PublishDateTime > DateTime.Now)
                    {
                        newsViewModel.FuturePublish = true;
                        newsViewModel.PersianPublishDate = news.FirstOrDefault().PublishDateTime.ConvertMiladiToShamsi("yyyy/MM/dd");
                        newsViewModel.PersianPublishTime = news.FirstOrDefault().PublishDateTime.Value.TimeOfDay.ToString();
                    }

                    newsViewModel.NewsCategoriesViewModel = new NewsCategoriesViewModel(await _uw.CategoryRepository.GetAllCategoriesAsync(), news.Select(n => n.IdOfCategories).Distinct().ToArray());
                    newsViewModel.NameOfTags = news.Select(t => t.NameOfTags).Distinct().ToArray().CombineWith(',');
                }
            }

            return View(newsViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(NewsViewModel viewModel, string submitButton) // قرار می گیرد submitButton مقدار وضعیت انتشار با تغییرات در بخش کاربر در متغیر
        {
            viewModel.Url = viewModel.Url.Trim();
            ViewBag.Tags = _uw.Context.Tags.Select(t => t.TagName).ToList();
            viewModel.NewsCategoriesViewModel = new NewsCategoriesViewModel(await _uw.CategoryRepository.GetAllCategoriesAsync(), viewModel.CategoryIds);  // پارامتر اول همه دسته ها بصورت ساختار درختی را می گیرد و پارامتر دوم برای دسته بندی های خبر است و چون در اینجا عمل درج انجام می شود پس هیچ دسته بندی ای برای اخبار انتخاب نکردیم // آی دی های جدید دسته بندی اخبار را داخل پراپرتی میریزیم


            if (!viewModel.FuturePublish)
            {
                ModelState.Remove("PersianPublishTime");
                ModelState.Remove("PersianPublishDate");
            }

            if (viewModel.NewsId.HasValue())
                ModelState.Remove("ImageFile");

            if (ModelState.IsValid)
            {
                if (submitButton != "ذخیره پیش نویس")
                    viewModel.IsPublish = true; // بصورت پیش فرض فالس است IsPublish مقدار

                if (viewModel.ImageFile != null)
                    viewModel.ImageName = $"news-{StringExtensions.GenerateId(10)}.jpg";

                if (viewModel.NewsId.HasValue())
                {
                    var news = _uw.BaseRepository<News>().FindByConditionAsync(n => n.NewsId == viewModel.NewsId, null, n => n.NewsCategories, n => n.NewsTags).Result.FirstOrDefault(); // با استفاده از ایگر لودینگ ایندو نویگیشن پراپرتی را لود میکنیم تا بتوانیم مقدار انها را ویرایش کنیم

                    if (news == null)
                        ModelState.AddModelError(string.Empty, NewsNotFound);
                    else
                    {
                        if (viewModel.IsPublish && news.IsPublish == false)
                            viewModel.PublishDateTime = DateTimeExtensions.DateTimeWithOutMilliSecends(DateTime.Now);

                        if (viewModel.IsPublish && news.IsPublish == true)
                        {

NewsWebsite/Areas/Admin/Controllers/TagController.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsWebsite.Common.Extensions;
using NewsWebsite.Data.Contracts;
using NewsWebsite.Entities;
using NewsWebsite.ViewModels.DynamicAccess;
using NewsWebsite.ViewModels.Tag;

namespace NewsWebsite.Areas.Admin.Controllers
{
    [DisplayName("مدیریت برچسب ها")]
    public class TagController : BaseController
    {
        private const string TagNotFound = "برچسب یافت نشد.";
        private const string TagDuplicate = "نام برچسب تکراری است.";
        private readonly IUnitOfWork _uw;
        private readonly IMapper _mapper;
        public TagController(IUnitOfWork uw, IMapper mapper)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }


        [HttpGet, DisplayName("مشاهده"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> GetTags(string search, string order, int offset, int limit, string sort)
        {
            List<TagViewModel> tags;
            int total = _uw.BaseRepository<Tag>().CountEntities();

            if (!search.HasValue())
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "برچسب")
            {
                if (order == "asc")
                    tags = await _uw.TagRepository.GetPaginateTagsAsync(offset, limit, "TagName", search);
                else
                    tags = await _uw.TagRepository.GetPaginateTagsAsync(offset, limit, "TagName desc", search);
            }
            else
                tags = await _uw.TagRepository.GetPaginateTagsAsync(offset, limit, "TagName", search);

            if (search != "")
                total = tags.Count();

            return Json(new { total = total, rows = tags });
        }


        [HttpGet, DisplayName("درج و ویرایش"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderTag(string tagId)
        {
            var tagViewModel = new TagViewModel();

            if (tagId.HasValue())
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(tagId);

                if (tag != null)
                    tagViewModel = _mapper.Map<TagViewModel>(tag);
                else
                    ModelState.AddModelError(string.Empty, TagNotFound);
            }

            return PartialView("_RenderTag", tagViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(TagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (_uw.TagRepository.IsExistTag(viewModel.TagName, viewModel.TagId))
                    ModelState.AddModelError(string.Empty, TagDuplicate);
                else
                {
                    if (viewModel.TagId.HasValue())
                    {
                        var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(viewModel.TagId);

                        if (tag != null)
                        {
                            _uw.BaseRepository<Tag>().Update(_mapper.Map(viewModel, tag));
                            await _uw.Commit();
                            TempData["notification"] = EditSuccess;
                        }
                        else
                            ModelState.AddModelError(string.Empty, TagNotFound);
                    }
                    else
                    {
                        viewModel.TagId = StringExtensions.GenerateId(10);
                        await _uw.BaseRepository<Tag>().CreateAsync(_mapper.Map<Tag>(viewModel));
                        await _uw.Commit();
                        TempData["notification"] = InsertSuccess;
                    }
                }
            }

            return PartialView("_RenderTag", viewModel);
        }


        [HttpGet, DisplayName("حذف"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string tagId)
        {
            if (!tagId.HasValue())
                ModelState.AddModelError(string.Empty, TagNotFound);
            else
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(tagId);

                if (tag == null)
                    ModelState.AddModelError(string.Empty, TagNotFound);
                else
                    return PartialView("_DeleteConfirmation", tag);
            }

            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Tag model)
        {
            if (model.TagId == null)
                ModelState.AddModelError(string.Empty, TagNotFound);
            else
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(model.TagId);

                if (tag == null)
                    ModelState.AddModelError(string.Empty, TagNotFound);
                else
                {
                    _uw.BaseRepository<Tag>().Delete(tag);
                    await _uw.Commit();
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation", tag);
                }
            }

            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("DeleteGroup"), DisplayName("حذف گروهی"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ برچسبی برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(item);
                    _uw.BaseRepository<Tag>().Delete(tag);
                }

                await _uw.Commit(); // وقتی همه تگ ها حذف شدند تغییرات در دیتابیس اعمال می شود
                TempData["notification"] = DeleteGroupSuccess;
            }

            return PartialView("_DeleteGroup");
        }
    }
}

NewsWebsite/Views/Shared/_AdminLayout.cshtml
@using NewsWebsite.Services.Contracts
@using NewsWebsite.Common.Extensions
@inject IApplicationUserManager userManager

@{
    var user = await userManager.GetUserAsync(User);
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>پنل مدیریت سایت خبری</title>

    <!-- Favicon -->
    <link href="/assets/img/favicon.png" rel="icon" type="image/png">
    <!-- Icons -->
    <link href="/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link href="/assets/vendor/fontawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="/assets/css/argon.css?v=1.0.0" rel="stylesheet">
    <script src="/assets/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/CacheFiles/js/Ajax.js" asp-append-version="true"></script>
    <!-- Loading -->
    <link href="~/CacheFiles/lib/Loading/css/preloader.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/CacheFiles/lib/Loading/js/jquery.preloader.min.js" asp-append-version="true"></script>
    <!-- Sweetalert2 -->
    <link href="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.js" asp-append-version="true"></script>
    <!-- DateTimePicker -->
    <link href="~/lib/bootstrap.datetimepicker/css/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />
    <script src="~/lib/bootstrap.datetimepicker/js/jquery.md.bootstrap.datetimepicker.js"></script>

    <link href="~/css/bootstrap-fileinput.css" rel="stylesheet" />
    <script src="~/js/bootstrap-fileinput.min.js"></script>
    <!-- Bootstrap Table -->
    <link href="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table.min.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table.js" asp-append-version="true"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/extensions/export/tableExport.js" asp-append-version="true"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table-locale-all.js" asp-append-version="true"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js" asp-append-version="true"></script>
</head>

<body>
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand pt-0" href="./index.html">
                <img src="/assets/img/Logo.png" class="navbar-brand-img" alt="...">
                پنل مدیریت میزفا
            </a>
            <ul class="nav align-items-center d-md-none">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                @if (user.Image.HasValue())
                                {
                                    <img alt="Image placeholder" src="~/avatars/@user.Image">
                                }
                                else
                                {
                                    <img alt="Image placeholder" src="~/assets/img/UserPic.png">
                                }
                            </span>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                        <a href="./examples/profile.html" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>نمایه من</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#!" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>خروج</span>
                        </a>
                    </div>
                </li>
            </ul>
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                        <div class="col-9 collapse-brand">
                            <a href="./index.html">
                                <img src="~/assets/img/Logo.png"> پنل مدیریت میزفا
                            </a>
                        </div>
                        <div class="col-3 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                <hr class="my-3">
                @await Html.PartialAsync("_AdminMenu")
            </div>
        </div>
    </nav>
    <div class="main-content">
        @RenderBody()

        <footer class="footer container-fluid">
            <div class="row align-items-center justify-content-xl-between">
                <div class="col-xl-6">
                    <div class="copyright text-center text-xl-left text-muted">
                        2020  &copy;  <a href="/Home/Index" class="font-weight-bold ml-1" target="_blank">سایت خبری میزفا</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="/assets/js/argon.js?v=1.0.0"></script>
    @RenderSection("Scripts", false)
</body>
</html>

NewsWebsite/Views/Shared/_AdminMenu.cshtml
@using NewsWebsite.Common.Extensions;
@addTagHelper*,NewsWebsite

<ul class="navbar-nav">
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Dashboard" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Dashboard">
                <i class="ni ni-tv-2 text-primary"></i> داشبورد
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Category" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Category">
                <i class="ni ni-bullet-list-67 text-red"></i> مدیریت دسته بندی ها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Tag" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Tag">
                <i class="ni ni-bullet-list-67 text-red"></i> مدیریت برچسب ها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="News" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="News">
                <i class="ni ni-folder-17 text-blue"></i> مدیریت اخبار
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="RoleManager" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="RoleManager">
                <i class="fa fa-user text-pink"></i> مدیریت نقش ها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="UserManager" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="UserManager">
                <i class="fa fa-users text-yellow"></i> مدیریت کاربران
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Video" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Video">
                <i class="fa fa-video text-primary"></i> مدیریت ویدیوها
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Comments" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Comments">
                <i class="fa fa-comments text-info"></i> مدیریت نظرات
            </a>
        </security-trimming>

    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="Newsletter" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Newsletter">
                <i class="ni ni-notification-70 text-danger"></i> مدیریت خبرنامه
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-action="ChangePassword" asp-controller="Manage">
            <i class="ni ni-key-25 text-info"></i> تغییر کلمه عبور
        </a>
    </li>
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="SiteSetting" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="SiteSetting">
                <i class="ni ni-settings-gear-65 text-suceess"></i> تنظیمات سایت
            </a>
        </security-trimming>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-action="ChangeTwoFactorEnabled" asp-controller="UserManager">
            <i class="ni ni-settings-gear-65 text-info"></i>  احراز هویت دو مرحله ای
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-action="Profile" asp-controller="Manage" asp-route-userId="@User.Identity.GetUserId()">
            <i class="ni ni-circle-08 text-pink"></i> نمایه من
        </a>
    </li>
</ul>

NewsWebsite/Views/Shared/_DeleteGroup.cshtml
<div class="modal fade" id="DeleteGroup" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">حذف گروهی</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                @{var IsValid = ViewData.ModelState.IsValid.ToString();}
                <input name="IsValid" type="hidden" value="@IsValid" />
                @if (IsValid == "False")
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما میخواهید موارد انتخاب شده را حذف کنید؟</h4>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-labeled  btn-danger" data-dismiss="modal">
                    @(IsValid == "True" ? "خیر" : "بستن")
                </button>
                @if (IsValid == "True")
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success mr-1" data-save="modal">
                        بله
                    </button>
                }
            </div>
        </div>
    </div>
</div>

NewsWebsite/Views/Shared/_RegisterInNewsletter.cshtml
@model NewsWebsite.ViewModels.Newsletter.NewsletterViewModel

<link href="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" asp-append-version="true" />
<script src="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.js" asp-append-version="true"></script>

<div class="single-widget newsletter-widget mb-4 border">
    <div class="section-heading style-2 mb-30">
        <h4>عضویت در خبرنامه</h4>
        <div class="line"></div>
    </div>
    <p>جهت دریافت جدیدترین اخبار ایمیل خود را وارد کنید.</p>
    <div class="newsletter-form">
        <form asp-action="RegisterInNewsLetter" asp-controller="NewsLetter" asp-area="Admin" method="post">
            <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
            <input asp-for="Email" class="form-control mb-15" placeholder="ایمیل خود را وارد کنید">
            <button type="button" class="btn vizew-btn w-100" data-save="Ajax">عضویت</button>
            @if (ViewData.ModelState.IsValid.ToString() == "False")
            {
                <div asp-validation-summary="All" class="alert alert-danger mt-2"></div>
            }
        </form>
    </div>
</div>