NewsWebsite/Areas/Admin/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsWebsite.Common.Extensions;
using NewsWebsite.Data.Contracts;
using NewsWebsite.Entities;
using NewsWebsite.ViewModels.Comments;
using NewsWebsite.ViewModels.DynamicAccess;

namespace NewsWebsite.Areas.Admin.Controllers
{
    [DisplayName("مدیریت دیدگاه ها")]
    public class CommentsController : BaseController
    {
        private const string CommentNotFound = "دیدگاه یافت نشد.";
        private readonly IUnitOfWork _uw;
        private readonly IMapper _mapper;
        public CommentsController(IUnitOfWork uw, IMapper mapper)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }


        [HttpGet, DisplayName("مشاهده"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index(string newsId, bool? isConfirm)
        {
            return View(nameof(Index), new CommentViewModel { NewsId = newsId, IsConfirm = isConfirm }); // در ویو ایندکس به آی دی خبر و بررسی تایید ان خبر نیاز داریم
        }


        [HttpGet]
        public async Task<IActionResult> GetComments(string search, string order, int offset, int limit, string sort, string newsId, bool? isConfirm)
        {
            List<CommentViewModel> comments;
            int total = _uw.BaseRepository<Comment>().CountEntities();

            if (!search.HasValue())
                search = "";

            if (limit == 0)
                limit = total;

            if (!newsId.HasValue())
                newsId = "";

            if (sort == "نام")
            {
                if (order == "asc")
                    comments = await _uw.CommentRepository.GetPaginateCommentsAsync(offset, limit, "Name", search, newsId, isConfirm);
                else
                    comments = await _uw.CommentRepository.GetPaginateCommentsAsync(offset, limit, "Name desc", search, newsId, isConfirm);
            }
            else if (sort == "ایمیل")
            {
                if (order == "asc")
                    comments = await _uw.CommentRepository.GetPaginateCommentsAsync(offset, limit, "Email", search, newsId, isConfirm);
                else
                    comments = await _uw.CommentRepository.GetPaginateCommentsAsync(offset, limit, "Email desc", search, newsId, isConfirm);
            }
            else if (sort == "تاریخ ارسال")
            {
                if (order == "asc")
                    comments = await _uw.CommentRepository.GetPaginateCommentsAsync(offset, limit, "PostageDateTime", search, newsId, isConfirm);
                else
                    comments = await _uw.CommentRepository.GetPaginateCommentsAsync(offset, limit, "PostageDateTime desc", search, newsId, isConfirm);
            }
            else
                comments = await _uw.CommentRepository.GetPaginateCommentsAsync(offset, limit, "PostageDateTime desc", search, newsId, isConfirm);

            if (search != "")
                total = comments.Count();

            return Json(new { total = total, rows = comments });
        }


        [HttpGet, DisplayName("حذف"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string commentId)
        {
            if (!commentId.HasValue())
                ModelState.AddModelError(string.Empty, CommentNotFound);
            else
            {
                var comment = await _uw.BaseRepository<Comment>().FindByIdAsync(commentId);

                if (comment == null)
                    ModelState.AddModelError(string.Empty, CommentNotFound);
                else
                    return PartialView("_DeleteConfirmation", comment);
            }

            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Comment model)
        {
            if (model.CommentId == null)
                ModelState.AddModelError(string.Empty, CommentNotFound);
            else
            {
                var comment = await _uw.BaseRepository<Comment>().FindByIdAsync(model.CommentId);

                if (comment == null)
                    ModelState.AddModelError(string.Empty, CommentNotFound);
                else
                {
                    _uw.BaseRepository<Comment>().Delete(comment);
                    await _uw.Commit();
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation", comment);
                }
            }

            return PartialView("_DeleteConfirmation");
        }


        [HttpGet, DisplayName("تایید و عدم تایید"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> ConfirmOrInconfirm(string commentId)
        {
            if (!commentId.HasValue())
                ModelState.AddModelError(string.Empty, CommentNotFound);
            else
            {
                var comment = await _uw.BaseRepository<Comment>().FindByIdAsync(commentId);

                if (comment == null)
                    ModelState.AddModelError(string.Empty, CommentNotFound);
                else
                    return PartialView("_ConfirmOrInconfirm", comment);
            }

            return PartialView("_ConfirmOrInconfirm");
        }


        [HttpPost]
        public async Task<IActionResult> ConfirmOrInconfirm(Comment model)
        {
            if (model.CommentId == null)
                ModelState.AddModelError(string.Empty, CommentNotFound);
            else
            {
                var comment = await _uw.BaseRepository<Comment>().FindByIdAsync(model.CommentId);

                if (comment == null)
                    ModelState.AddModelError(string.Empty, CommentNotFound);
                else
                {
                    if (comment.IsConfirm)
                        comment.IsConfirm = false;
                    else
                        comment.IsConfirm = true;

                    _uw.BaseRepository<Comment>().Update(comment);
                    await _uw.Commit();
                    TempData["notification"] = OperationSuccess;
                    return PartialView("_ConfirmOrInconfirm", comment);
                }
            }

            return PartialView("_ConfirmOrInconfirm");
        }


        [HttpPost, ActionName("DeleteGroup"), DisplayName("حذف گروهی"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ دیدگاهی برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var comment = await _uw.BaseRepository<Comment>().FindByIdAsync(item);
                    _uw.BaseRepository<Comment>().Delete(comment);
                }

                await _uw.Commit();
                TempData["notification"] = DeleteGroupSuccess;
            }

            return PartialView("_DeleteGroup");
        }


        [HttpGet]
        public IActionResult SendComment(string parentCommentId, string newsId)
        {
            return PartialView("_SendComment", new CommentViewModel(parentCommentId, newsId));
        }


        [HttpPost]
        public async Task<IActionResult> SendComment(CommentViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.PostageDateTime = DateTimeExtensions.DateTimeWithOutMilliSecends(DateTime.Now);
                viewModel.CommentId = StringExtensions.GenerateId(10);
                await _uw.BaseRepository<Comment>().CreateAsync(_mapper.Map<Comment>(viewModel));
                await _uw.Commit();
                TempData["notification"] = "دیدگاه شما با موفقیت ارسال شد و بعد از تایید در سایت نمایش داده می شود.";
            }

            return PartialView("_SendComment", viewModel);
        }
    }
}

NewsWebsite/Areas/Admin/Controllers/TagController.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsWebsite.Common.Extensions;
using NewsWebsite.Data.Contracts;
using NewsWebsite.Entities;
using NewsWebsite.ViewModels.DynamicAccess;
using NewsWebsite.ViewModels.Tag;

namespace NewsWebsite.Areas.Admin.Controllers
{
    [DisplayName("مدیریت برچسب ها")]
    public class TagController : BaseController
    {
        private const string TagNotFound = "برچسب یافت نشد.";
        private const string TagDuplicate = "نام برچسب تکراری است.";
        private readonly IUnitOfWork _uw;
        private readonly IMapper _mapper;
        public TagController(IUnitOfWork uw, IMapper mapper)
        {
            _uw = uw;
            _uw.CheckArgumentIsNull(nameof(_uw));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }


        [HttpGet, DisplayName("مشاهده"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> GetTags(string search, string order, int offset, int limit, string sort)
        {
            List<TagViewModel> tags;
            int total = _uw.BaseRepository<Tag>().CountEntities();

            if (!search.HasValue())
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "برچسب")
            {
                if (order == "asc")
                    tags = await _uw.TagRepository.GetPaginateTagsAsync(offset, limit, "TagName", search);
                else
                    tags = await _uw.TagRepository.GetPaginateTagsAsync(offset, limit, "TagName desc", search);
            }
            else
                tags = await _uw.TagRepository.GetPaginateTagsAsync(offset, limit, "TagName", search);

            if (search != "")
                total = tags.Count();

            return Json(new { total = total, rows = tags });
        }


        [HttpGet, DisplayName("درج و ویرایش"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderTag(string tagId)
        {
            var tagViewModel = new TagViewModel();

            if (tagId.HasValue())
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(tagId);

                if (tag != null)
                    tagViewModel = _mapper.Map<TagViewModel>(tag);
                else
                    ModelState.AddModelError(string.Empty, TagNotFound);
            }

            return PartialView("_RenderTag", tagViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(TagViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (_uw.TagRepository.IsExistTag(viewModel.TagName, viewModel.TagId))
                    ModelState.AddModelError(string.Empty, TagDuplicate);
                else
                {
                    if (viewModel.TagId.HasValue())
                    {
                        var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(viewModel.TagId);

                        if (tag != null)
                        {
                            _uw.BaseRepository<Tag>().Update(_mapper.Map(viewModel, tag));
                            await _uw.Commit();
                            TempData["notification"] = EditSuccess;
                        }
                        else
                            ModelState.AddModelError(string.Empty, TagNotFound);
                    }
                    else
                    {
                        viewModel.TagId = StringExtensions.GenerateId(10);
                        await _uw.BaseRepository<Tag>().CreateAsync(_mapper.Map<Tag>(viewModel));
                        await _uw.Commit();
                        TempData["notification"] = InsertSuccess;
                    }
                }
            }

            return PartialView("_RenderTag", viewModel);
        }


        [HttpGet, DisplayName("حذف"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string tagId)
        {
            if (!tagId.HasValue())
                ModelState.AddModelError(string.Empty, TagNotFound);
            else
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(tagId);

                if (tag == null)
                    ModelState.AddModelError(string.Empty, TagNotFound);
                else
                    return PartialView("_DeleteConfirmation", tag);
            }

            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Tag model)
        {
            if (model.TagId == null)
                ModelState.AddModelError(string.Empty, TagNotFound);
            else
            {
                var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(model.TagId);

                if (tag == null)
                    ModelState.AddModelError(string.Empty, TagNotFound);
                else
                {
                    _uw.BaseRepository<Tag>().Delete(tag);
                    await _uw.Commit();
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation", tag);
                }
            }

            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("DeleteGroup"), DisplayName("حذف گروهی"), Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ برچسبی برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var tag = await _uw.BaseRepository<Tag>().FindByIdAsync(item);
                    _uw.BaseRepository<Tag>().Delete(tag);
                }

                await _uw.Commit(); // وقتی همه تگ ها حذف شدند تغییرات در دیتابیس اعمال می شود
                TempData["notification"] = DeleteGroupSuccess;
            }

            return PartialView("_DeleteGroup");
        }
    }
}

NewsWebsite/Areas/Admin/Views/Comments/Index.cshtml
@model NewsWebsite.ViewModels.Comments.CommentViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html">مدیریت نظرات</a>
            </li>
        </ul>
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>

<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8"></div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                مدیریت نظرات
            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="Comments">
                    @await Html.PartialAsync("_CommentsTable", Model)
                </form>
            </div>
        </div>
    </div>
</div>

NewsWebsite/Areas/Admin/Views/Comments/_CommentsTable.cshtml
@model NewsWebsite.ViewModels.Comments.CommentViewModel
@using NewsWebsite.Services.Contracts
@inject ISecurityTrimmingService securityTrimmingService

<div id="toolbar">
    <button type="button" class="btn btn-danger" data-toggle="ajax-modal" data-url="@Url.Action("DeleteGroup","Tag")">
        <i class="fa fa-trash"></i> | حذف گروهی
    </button>
</div>
<table id="table"
       data-toolbar="#toolbar"
       data-search="true"
       data-show-refresh="true"
       data-show-toggle="true"
       data-show-fullscreen="true"
       data-show-columns="true"
       data-detail-view="true"
       data-show-export="true"
       data-click-to-select="true"
       data-detail-formatter="detailFormatter"
       data-minimum-count-columns="2"
       data-show-pagination-switch="true"
       data-pagination="true"
       data-id-field="id"
       data-page-list="[10, 25, 50, 100, all]"
       data-show-footer="true"
       data-side-pagination="server"
       data-url="/Admin/Comments/GetComments?newsId=@Model.NewsId&&isConfirm=@Model.IsConfirm"
       data-response-handler="responseHandler">
</table>

<script>
    var $table = $('#table')
    var selections = []

    function get_query_params(p) {
        return {
            extraParam: 'abc',
            search: p.title,
            sort: p.sort,
            order: p.order,
            limit: p.limit,
            offset: p.offset
        }
    }

    function responseHandler(res) {
        $.each(res.rows, function (i, row) {
            row.state = $.inArray(row.id, selections) !== -1
        })
        return res
    }

    function detailFormatter(index, row) {
            var html = []
            $.each(row, function (key, value) {
                if (key != "state" && key != "Id" && key!="ردیف" && key!="IsConfirm")
                    html.push('<p><b>' + key + ':</b> ' + value + '</p>')
            })
            return html.join('')
    }

    function operateFormatter(value, row, index) {
        var access = "";
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","Comments","ConfirmOrInconfirm")' == 'True') {
            access = access + '<button type="button" class="btn-link text-success" data-toggle="ajax-modal" data-url=@Url.Action("ConfirmOrInconfirm", "Comments")?commentId=' + row.Id + ' title="تایید / عدم تایید"><i class="fa fa-check"></i></button>';
        }
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","Comments","Delete")' == 'True') {
            access = access + '<button type="button" class="btn-link text-danger" data-toggle="ajax-modal" data-url=@Url.Action("Delete", "Comments")/?commentId=' + row.Id + ' title="حذف"><i class="fa fa-trash"></i></button>';
        }
        return access;
    }

    function isConfirmFormatter(value, row, index) {
       var spanClass = "badge badge-success";
       var IsConfirm = "تایید شده";
       if (!row.IsConfirm) {
           IsConfirm = "تایید نشده";
           spanClass = "badge badge-danger";
       }
        return [
           '<span class="' + spanClass + '">' + IsConfirm + '</span>'
        ].join('')
    }

    function checkBoxFormat(value, row) {
       return '<input type="checkbox" name="btSelectItem" value="' + row.Id + '" />';
    }

    function totalTextFormatter(data) {
        return 'تعداد'
    }

    function totalNameFormatter(data) {
        return data.length
    }

    function initTable() {
        $table.bootstrapTable('destroy').bootstrapTable({
            height: 600,
            locale: 'fa-IR',
            columns: [
                [{
                    field: 'state',
                    checkbox: true,
                    rowspan: 2,
                    align: 'center',
                    valign: 'middle',
                    formatter: checkBoxFormat
                }, {
                    title: 'ردیف',
                    field: 'ردیف',
                    rowspan: 2,
                    align: 'center',
                    valign: 'middle',
                    footerFormatter: totalTextFormatter
                }, {
                    title: 'جزئیات اطلاعات دیدگاه ها',
                    colspan: 5,
                    align: 'center'
                }],
                [{
                    field: 'نام',
                    title: 'نام',
                    sortable: true,
                    footerFormatter: totalNameFormatter,
                },{
                    field: 'ایمیل',
                    title: 'ایمیل',
                    sortable: true,
                },{
                    field: 'تاریخ ارسال',
                    title: 'تاریخ ارسال',
                    align: 'center',
                    sortable: true,
                },{
                    field: 'وضعیت',
                    title: 'وضعیت',
                    align: 'center',
                    sortable: true,
                    formatter: isConfirmFormatter
                },{
                    field: 'operate',
                    title: 'عملیات',
                    align: 'center',
                    events: window.operateEvents,
                    formatter: operateFormatter
                }]
            ]
        })
    }

    $(function () {
        initTable()
        $('#locale').change(initTable)
    })
</script>

NewsWebsite/Areas/Admin/Views/Comments/_ConfirmOrInconfirm.cshtml
@model NewsWebsite.Entities.Comment

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">@(Model.IsConfirm ? "عدم تایید دیدگاه" : "تایید دیدگاه")</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body clearfix">
                @if (Model == null)
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما می خواهید دیدگاه کاربر با ایمیل @Model.Email را @(Model.IsConfirm ? "عدم تایید" : "تایید") کنید ؟</h4>
                    <form asp-action="ConfirmOrInconfirm">
                        <input name="IsValid" type="hidden" value="True" />
                        <input type="hidden" asp-for="CommentId" />
                    </form>
                }
            </div>

            <div class="modal-footer">
                @if (Model != null)
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                        بله
                    </button>
                }
                <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                    @(Model != null ? "خیر" : "بستن")
                </button>
            </div>
        </div>
    </div>
</div>

NewsWebsite/Areas/Admin/Views/Comments/_DeleteConfirmation.cshtml
@model NewsWebsite.Entities.Comment

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">حذف اطلاعات</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body clearfix">
                @if (Model == null)
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما می خواهید دیدگاه کاربر با ایمیل @Model.Email را حذف کنید ؟</h4>
                    <form asp-action="Delete">
                        <input name="IsValid" type="hidden" value="True" />
                        <input type="hidden" asp-for="CommentId" />
                    </form>
                }
            </div>

            <div class="modal-footer">
                @if (Model != null)
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                        بله
                    </button>
                }
                <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                    @(Model != null ? "خیر" : "بستن")
                </button>
            </div>
        </div>
    </div>
</div>